### 6. 异常

如果执行try块里面的逻辑代码出现异常,系统会自动生成一个异常对象.该异常对象被提交给java运行时环境.这个过程叫做**抛出异常**.
当java运行时环境收到异常时,会寻找能处理该异常的catch块.如果找到合适的catch块,则把异常交给catch块处理.这个过程称为**捕获异常**.
如果不能找到捕获异常的catch块,则运行时环境终止,程序也将退出.

#### 异常类的继承体系

java中所有非正常情况分为两种:异常(Exception)和错误(Error).它们都继承Throwable.

#### 自定义异常

自定义异常都要继承Exception类.自定义Runtime异常,应该继承RuntimeException.需要提供两个构造器.一个是无参构造器,一个是带一个字符串参数的构造器,这个字符串代表异常对象的描述信息.

```java
class myselfException extends Exception{

    public myselfException(){}
    public myselfException(String msg){
        super(msg);
    }
}

public class ExceptionTest {

    public static void main(String[] args) throws myselfException {
        int a = 5;
        if(a == 5){
            throw new myselfException("a不能等于5");
        }

    }
}
```

#### 异常链

捕获一个异常,抛出另一个异常,并把原始异常信息保存下来是一种典型的链式处理(职责链模式),也被称为"异常链".